// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(WineCellarContext))]
    [Migration("20241020035417_AgregamosCataYRelacion")]
    partial class AgregamosCataYRelacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CataWine", b =>
                {
                    b.Property<int>("CataId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WinesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CataId", "WinesId");

                    b.HasIndex("WinesId");

                    b.ToTable("CataWine");
                });

            modelBuilder.Entity("Data.Entities.Cata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Invitados")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Catas");
                });

            modelBuilder.Entity("Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "Pa$$w0rd",
                            Rol = 0,
                            UserName = "karenbailapiola@gmail.com"
                        },
                        new
                        {
                            Id = 2,
                            Password = "SecureP@ss",
                            Rol = 0,
                            UserName = "juanperez@gmail.com"
                        });
                });

            modelBuilder.Entity("Data.Entities.Wine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Variety")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Wines");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 10, 20, 3, 54, 16, 497, DateTimeKind.Utc).AddTicks(8103),
                            Name = "Malbec",
                            Region = "Mendoza",
                            Stock = 30,
                            Variety = "Malbec",
                            Year = 2020
                        },
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 10, 20, 3, 54, 16, 497, DateTimeKind.Utc).AddTicks(8098),
                            Name = "Cabernet Sauvignon",
                            Region = "Mendoza",
                            Stock = 50,
                            Variety = "Cabernet Sauvignon",
                            Year = 2018
                        });
                });

            modelBuilder.Entity("CataWine", b =>
                {
                    b.HasOne("Data.Entities.Cata", null)
                        .WithMany()
                        .HasForeignKey("CataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Entities.Wine", null)
                        .WithMany()
                        .HasForeignKey("WinesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
